#!/usr/bin/env python3
"""Refresh GrowthGrind's vetted public opportunity sources.

This deliberately imports only named providers and direct programme pages. It
does not scrape Google results, AI answers, social posts, or arbitrary sites.
Evergreen entries point students to a provider's current opportunities page;
the daily run updates them and leaves deadline fields empty rather than inventing
dates. Add a provider only after checking its public terms and student fit.
"""
import os
from supabase import create_client

SUPABASE_URL = os.environ.get("SUPABASE_URL")
SUPABASE_KEY = os.environ.get("SUPABASE_KEY")

SOURCES = [
    {"title": "The R3cruit 16–18 opportunities", "provider": "The R3cruit", "category": "Careers", "activity_type": "Work Experience", "location": "UK", "format": "Online and in-person", "age_range": "16-18", "cost": "Free", "subjects": "Finance, Business, Technology, Engineering", "link": "https://ther3cruit.co.uk/16-18-opportunities/", "description": "Frequently updated work experience, insight programmes, apprenticeships and career opportunities for 16–18-year-olds. Open the listing for live deadlines and direct application details."},
    {"title": "Prospects work experience and internships", "provider": "Prospects", "category": "Careers", "activity_type": "Work Experience", "location": "UK", "format": "Online and in-person", "age_range": "Check opportunity", "cost": "Free", "subjects": "General / All Sectors", "link": "https://www.prospects.ac.uk/jobs-and-work-experience/work-experience-and-internships/", "description": "Current guidance and routes to work experience and internships across sectors. Check individual opportunities for eligibility and application dates."},
    {"title": "The Brokerage Talent Network", "provider": "The Brokerage", "category": "Careers", "activity_type": "Work Experience", "location": "London / UK", "format": "Online and in-person", "age_range": "16-25", "cost": "Free", "subjects": "Business, Finance, Technology, General / All Sectors", "link": "https://www.thebrokerage.org.uk/talent-network", "description": "Talent network offering routes to internships, paid roles, employability support and employer opportunities for young people. Check current eligibility and openings directly."},
    {"title": "Futures for All opportunity finder", "provider": "Futures for All", "category": "Careers", "activity_type": "Opportunity Directory", "location": "UK", "format": "Online and in-person", "age_range": "Check opportunity", "cost": "Free", "subjects": "General / All Sectors", "link": "https://finder.futuresforall.org/opportunity-search?sortBy=AdvertiseStartAt&sortDirection=Ascending", "description": "Search a live directory of employer, education and skills opportunities. Use its filters to find currently open programmes and check each provider’s application requirements."},
    {"title": "Sutton Trust Pathways and UK Summer Schools", "provider": "The Sutton Trust", "category": "Academic", "activity_type": "Summer School", "location": "UK", "format": "Online and in-person", "age_range": "Year 12 / equivalent — check programme", "cost": "Free", "subjects": "Medicine, Law, Engineering, Finance, General / All Sectors", "link": "https://www.suttontrust.com/our-programmes/", "description": "Free widening-participation programmes, including Pathways, UK Summer Schools and online support. Check current eligibility, partner universities and application dates on the official Sutton Trust page."},
    {"title": "Oxford University outreach programmes", "provider": "University of Oxford", "category": "Academic", "activity_type": "University Outreach", "location": "UK", "format": "Online and in-person", "age_range": "Year 10+ / check programme", "cost": "Free", "subjects": "General / All Sectors", "link": "https://www.ox.ac.uk/admissions/undergraduate/access-oxford/outreach-programmes", "description": "Oxford's official access programmes, including UNIQ and BeUNIQ. Check individual programme eligibility, year-group and application details."},
    {"title": "Oxford University outreach events", "provider": "University of Oxford", "category": "Academic", "activity_type": "University Outreach", "location": "UK", "format": "Online and in-person", "age_range": "Check event", "cost": "Free / check event", "subjects": "General / All Sectors", "link": "https://www.ox.ac.uk/admissions/undergraduate/access-oxford/outreach-events", "description": "Oxford's current official outreach events, student conferences, subject taster activities and university-application information."},
    {"title": "Cambridge University widening participation and outreach", "provider": "University of Cambridge", "category": "Academic", "activity_type": "University Outreach", "location": "UK", "format": "Online and in-person", "age_range": "Check programme", "cost": "Free / check programme", "subjects": "General / All Sectors", "link": "https://www.cam.ac.uk/study-at-cambridge/widening-participation", "description": "Cambridge's official widening-participation and outreach information. Explore current events, regional programmes and school-student support."},
    {"title": "UCL widening participation opportunities", "provider": "University College London", "category": "Academic", "activity_type": "University Outreach", "location": "UK", "format": "Online and in-person", "age_range": "Check programme", "cost": "Free / check programme", "subjects": "General / All Sectors", "link": "https://www.ucl.ac.uk/prospective-students/widening-participation", "description": "UCL's official widening-participation programmes and resources for prospective students. Check individual eligibility and current events."},
    {"title": "Warwick University outreach and widening participation", "provider": "University of Warwick", "category": "Academic", "activity_type": "University Outreach", "location": "UK", "format": "Online and in-person", "age_range": "Check programme", "cost": "Free / check programme", "subjects": "General / All Sectors", "link": "https://warwick.ac.uk/study/outreach/", "description": "Warwick's official outreach and widening-participation activity for school and college students. Check programme availability and eligibility."},
    {"title": "Forage virtual job simulations", "provider": "Forage", "category": "Careers", "activity_type": "Virtual Work Experience", "location": "International / online", "format": "Online", "age_range": "Check provider eligibility", "cost": "Free", "subjects": "Business, Technology, Law, Finance", "link": "https://www.theforage.com/", "description": "Free employer-designed virtual job simulations. Browse current programmes and complete one at your own pace; availability and eligibility are shown by the provider."},
    {"title": "Springpod virtual work experience", "provider": "Springpod", "category": "Careers", "activity_type": "Virtual Work Experience", "location": "UK / online", "format": "Online", "age_range": "Check provider eligibility", "cost": "Free / check provider", "subjects": "Medicine, Business, Law, Technology, Engineering", "link": "https://www.springpod.com/virtual-work-experience", "description": "Browse current virtual work-experience programmes and provider eligibility directly with Springpod."},
    {"title": "Speakers for Schools work experience", "provider": "Speakers for Schools", "category": "Careers", "activity_type": "Work Experience", "location": "UK", "format": "Online and in-person", "age_range": "Check provider eligibility", "cost": "Free", "subjects": "General / All Sectors", "link": "https://www.speakersforschools.org/experience/", "description": "Current work-experience opportunities for young people. Check the provider page for open placements, dates and eligibility."},
    {"title": "Nuffield Research Placements", "provider": "Nuffield Foundation", "category": "Academic", "activity_type": "Research", "location": "UK", "format": "In-person and hybrid", "age_range": "Post-16 / check provider", "cost": "Free", "subjects": "Science, Research & Sustainability", "link": "https://www.nuffieldresearchplacements.org/", "description": "Research placements for eligible post-16 students. Check regional availability, timetable and application criteria on the official page."},
    {"title": "FutureLearn short courses and certificates", "provider": "FutureLearn", "category": "Academic", "activity_type": "Course / Programme", "location": "International / online", "format": "Online", "age_range": "Check provider eligibility", "cost": "Free and paid options", "subjects": "General / All Sectors", "link": "https://www.futurelearn.com/courses", "description": "Explore current online short courses from universities and cultural institutions. Course access and certificate options vary."},
    {"title": "OpenLearn free courses", "provider": "The Open University", "category": "Academic", "activity_type": "Course / Programme", "location": "International / online", "format": "Online", "age_range": "Open access / check course", "cost": "Free", "subjects": "General / All Sectors", "link": "https://www.open.edu/openlearn/free-courses", "description": "Free online courses across subjects. Check individual course pages for study time and digital badges."},
    {"title": "National Saturday Club", "provider": "National Saturday Club", "category": "Creative", "activity_type": "Course / Programme", "location": "UK", "format": "In-person", "age_range": "13-16", "cost": "Free", "subjects": "Art, Design, Technology", "link": "https://www.nationalsaturdayclub.org/", "description": "Saturday clubs in art, design, science, technology and performance. Check local club availability and current application details."},
    {"title": "Duke of Edinburgh's Award", "provider": "DofE", "category": "Leadership", "activity_type": "Leadership Programme", "location": "International", "format": "In-person and hybrid", "age_range": "14+", "cost": "Check provider", "subjects": "Leadership, Volunteering, Sport", "link": "https://www.dofe.org/", "description": "Structured volunteering, physical, skills and expedition challenges. Check local centre availability and participation costs."},
    {"title": "Do-it volunteering opportunities", "provider": "Do-it", "category": "Volunteering", "activity_type": "Volunteering", "location": "UK", "format": "Online and in-person", "age_range": "Check organisation eligibility", "cost": "Free", "subjects": "General / All Sectors", "link": "https://doit.life/", "description": "Search current volunteering roles by location and cause. Each organisation sets its own age and safeguarding requirements."},
    {"title": "British Science Association CREST Awards", "provider": "British Science Association", "category": "Academic", "activity_type": "Research", "location": "UK and international", "format": "Online and in-person", "age_range": "11-19", "cost": "Check provider", "subjects": "Science, Research & Sustainability", "link": "https://www.crestawards.org/", "description": "Student-led STEM project awards. Check current project formats, costs and school participation guidance."},
    {"title": "UK Mathematics Trust competitions", "provider": "UK Mathematics Trust", "category": "Academic", "activity_type": "Competition", "location": "UK", "format": "School-based", "age_range": "Check competition", "cost": "Check school / provider", "subjects": "Mathematics", "link": "https://ukmt.org.uk/competitions", "description": "Current mathematics challenges, olympiads and team competitions. Check the relevant competition’s year-group and entry details."},
    {"title": "Erasmus+ Youth opportunities", "provider": "European Youth Portal", "category": "International", "activity_type": "International Programme", "location": "International", "format": "Online and in-person", "age_range": "Check opportunity", "cost": "Varies", "subjects": "Languages, Leadership, Volunteering", "link": "https://youth.europa.eu/go-abroad_en", "description": "Explore current international youth exchanges, volunteering and mobility opportunities. Eligibility depends on residence, age and host programme."},
]


def record(source):
    return {**source, "deadline": None, "year_groups": None, "interests": None}


def main():
    if not SUPABASE_URL or not SUPABASE_KEY:
        raise SystemExit("Set SUPABASE_URL and SUPABASE_KEY GitHub secrets before running.")
    client = create_client(SUPABASE_URL, SUPABASE_KEY)
    inserted, updated = 0, 0
    for source in SOURCES:
        data = record(source)
        existing = client.table("opportunities").select("id").eq("link", source["link"]).limit(1).execute()
        if existing.data:
            client.table("opportunities").update(data).eq("id", existing.data[0]["id"]).execute()
            updated += 1
        else:
            client.table("opportunities").insert(data).execute()
            inserted += 1
    print(f"Verified public-source refresh complete: {inserted} inserted, {updated} updated.")


if __name__ == "__main__":
    main()
