#!/usr/bin/env python3
"""Refresh GrowthGrind's vetted public opportunity sources.

This deliberately imports only named providers and direct programme pages. It
does not scrape Google results, AI answers, social posts, or arbitrary sites.
Evergreen entries point students to a provider's current opportunities page;
the daily run updates them and leaves deadline fields empty rather than inventing
dates. Add a provider only after checking its public terms and student fit.
"""
import os
from supabase import create_client

SUPABASE_URL = os.environ.get("SUPABASE_URL")
SUPABASE_KEY = os.environ.get("SUPABASE_KEY")

SOURCES = [
    {"title": "The R3cruit 16–18 opportunities", "provider": "The R3cruit", "category": "Careers", "activity_type": "Work Experience", "location": "UK", "format": "Online and in-person", "age_range": "16-18", "cost": "Free", "subjects": "Finance, Business, Technology, Engineering", "link": "https://ther3cruit.co.uk/16-18-opportunities/", "description": "Frequently updated work experience, insight programmes, apprenticeships and career opportunities for 16–18-year-olds. Open the listing for live deadlines and direct application details."},
    {"title": "Prospects work experience and internships", "provider": "Prospects", "category": "Careers", "activity_type": "Work Experience", "location": "UK", "format": "Online and in-person", "age_range": "Check opportunity", "cost": "Free", "subjects": "General / All Sectors", "link": "https://www.prospects.ac.uk/jobs-and-work-experience/work-experience-and-internships/", "description": "Current guidance and routes to work experience and internships across sectors. Check individual opportunities for eligibility and application dates."},
    {"title": "The Brokerage Talent Network", "provider": "The Brokerage", "category": "Careers", "activity_type": "Work Experience", "location": "London / UK", "format": "Online and in-person", "age_range": "16-25", "cost": "Free", "subjects": "Business, Finance, Technology, General / All Sectors", "link": "https://www.thebrokerage.org.uk/talent-network", "description": "Talent network offering routes to internships, paid roles, employability support and employer opportunities for young people. Check current eligibility and openings directly."},
    {"title": "Futures for All opportunity finder", "provider": "Futures for All", "category": "Careers", "activity_type": "Opportunity Directory", "location": "UK", "format": "Online and in-person", "age_range": "Check opportunity", "cost": "Free", "subjects": "General / All Sectors", "link": "https://finder.futuresforall.org/opportunity-search?sortBy=AdvertiseStartAt&sortDirection=Ascending", "description": "Search a live directory of employer, education and skills opportunities. Use its filters to find currently open programmes and check each provider’s application requirements."},
    {"title": "Sutton Trust Pathways and UK Summer Schools", "provider": "The Sutton Trust", "category": "Academic", "activity_type": "Summer School", "location": "UK", "format": "Online and in-person", "age_range": "Year 12 / equivalent — check programme", "cost": "Free", "subjects": "Medicine, Law, Engineering, Finance, General / All Sectors", "link": "https://www.suttontrust.com/our-programmes/", "description": "Free widening-participation programmes, including Pathways, UK Summer Schools and online support. Check current eligibility, partner universities and application dates on the official Sutton Trust page."},
    {"title": "Oxford University outreach programmes", "provider": "University of Oxford", "category": "Academic", "activity_type": "University Outreach", "location": "UK", "format": "Online and in-person", "age_range": "Year 10+ / check programme", "cost": "Free", "subjects": "General / All Sectors", "link": "https://www.ox.ac.uk/admissions/undergraduate/access-oxford/outreach-programmes", "description": "Oxford's official access programmes, including UNIQ and BeUNIQ. Check individual programme eligibility, year-group and application details."},
    {"title": "Oxford University outreach events", "provider": "University of Oxford", "category": "Academic", "activity_type": "University Outreach", "location": "UK", "format": "Online and in-person", "age_range": "Check event", "cost": "Free / check event", "subjects": "General / All Sectors", "link": "https://www.ox.ac.uk/admissions/undergraduate/access-oxford/outreach-events", "description": "Oxford's current official outreach events, student conferences, subject taster activities and university-application information."},
    {"title": "Cambridge University widening participation and outreach", "provider": "University of Cambridge", "category": "Academic", "activity_type": "University Outreach", "location": "UK", "format": "Online and in-person", "age_range": "Check programme", "cost": "Free / check programme", "subjects": "General / All Sectors", "link": "https://www.cam.ac.uk/study-at-cambridge/widening-participation", "description": "Cambridge's official widening-participation and outreach information. Explore current events, regional programmes and school-student support."},
    {"title": "UCL widening participation opportunities", "provider": "University College London", "category": "Academic", "activity_type": "University Outreach", "location": "UK", "format": "Online and in-person", "age_range": "Check programme", "cost": "Free / check programme", "subjects": "General / All Sectors", "link": "https://www.ucl.ac.uk/prospective-students/widening-participation", "description": "UCL's official widening-participation programmes and resources for prospective students. Check individual eligibility and current events."},
    {"title": "Warwick University outreach and widening participation", "provider": "University of Warwick", "category": "Academic", "activity_type": "University Outreach", "location": "UK", "format": "Online and in-person", "age_range": "Check programme", "cost": "Free / check programme", "subjects": "General / All Sectors", "link": "https://warwick.ac.uk/study/outreach/", "description": "Warwick's official outreach and widening-participation activity for school and college students. Check programme availability and eligibility."},
    {"title": "Imperial College London widening participation", "provider": "Imperial College London", "category": "Academic", "activity_type": "University Outreach", "location": "London / UK", "format": "Online and in-person", "age_range": "Check programme", "cost": "Free / check programme", "subjects": "STEM, Medicine, General / All Sectors", "link": "https://www.imperial.ac.uk/widening-participation/", "description": "Imperial's official widening-participation hub for prospective students. Explore current access programmes, outreach events and eligibility on the university page."},
    {"title": "LSE schools and colleges widening participation", "provider": "London School of Economics and Political Science", "category": "Academic", "activity_type": "University Outreach", "location": "London / UK", "format": "Online and in-person", "age_range": "Check programme", "cost": "Free / check programme", "subjects": "Economics, Politics, Law, Social Sciences, General / All Sectors", "link": "https://www.lse.ac.uk/study-at-lse/undergraduate/widening-participation/teachers-and-schools", "description": "LSE's official schools, colleges and widening-participation information, including current events and support for prospective students."},
    {"title": "King's College London schools and colleges outreach", "provider": "King's College London", "category": "Academic", "activity_type": "University Outreach", "location": "London / UK", "format": "Online and in-person", "age_range": "Check programme", "cost": "Free / check programme", "subjects": "Medicine, Law, Health, Humanities, General / All Sectors", "link": "https://www.kcl.ac.uk/study/schools-and-colleges", "description": "King's official schools and colleges hub for outreach activities, events and guidance for prospective students."},
    {"title": "University of Bristol outreach and widening participation", "provider": "University of Bristol", "category": "Academic", "activity_type": "University Outreach", "location": "Bristol / UK", "format": "Online and in-person", "age_range": "Check programme", "cost": "Free / check programme", "subjects": "General / All Sectors", "link": "https://www.bristol.ac.uk/study/undergraduate/access-and-participation-plan/", "description": "Bristol's official access and participation hub, linking to outreach and widening-participation opportunities for schools, young people and mature students."},
    {"title": "University of Birmingham widening participation", "provider": "University of Birmingham", "category": "Academic", "activity_type": "University Outreach", "location": "Birmingham / UK", "format": "Online and in-person", "age_range": "Year 6-13 / check programme", "cost": "Free / check programme", "subjects": "Medicine, Law, Engineering, General / All Sectors", "link": "https://www.birmingham.ac.uk/study/undergraduate/schools-and-colleges/widening-participation", "description": "Birmingham's official widening-participation programmes, including Pathways to Birmingham, pre-16 activity and application support."},
    {"title": "University of Leeds access and outreach", "provider": "University of Leeds", "category": "Academic", "activity_type": "University Outreach", "location": "Leeds / UK", "format": "Online and in-person", "age_range": "Year 7+ / check programme", "cost": "Free / check programme", "subjects": "Arts, Health, Social Sciences, STEM, General / All Sectors", "link": "https://accessandoutreach.leeds.ac.uk/", "description": "Leeds' official access and outreach hub for pre-entry programmes, subject activities, school support and widening-access schemes."},
    {"title": "University of Manchester widening participation", "provider": "University of Manchester", "category": "Academic", "activity_type": "University Outreach", "location": "Manchester / UK", "format": "Online and in-person", "age_range": "Check programme", "cost": "Free / check programme", "subjects": "General / All Sectors", "link": "https://www.manchester.ac.uk/about/social-responsibility/social-inclusion/widening-participation/", "description": "Manchester's official widening-participation hub. Explore access schemes, outreach support and current opportunities for prospective students."},
    {"title": "University of Sheffield Access to Sheffield", "provider": "University of Sheffield", "category": "Academic", "activity_type": "University Outreach", "location": "Sheffield / UK", "format": "Online and in-person", "age_range": "Year 9-13 / check programme", "cost": "Free / check programme", "subjects": "General / All Sectors", "link": "https://www.sheffield.ac.uk/schools/programmes", "description": "Sheffield's official Access to Sheffield hub, with widening-access programmes, post-16 summer schools and application support."},
    {"title": "University of Nottingham widening participation programmes", "provider": "University of Nottingham", "category": "Academic", "activity_type": "University Outreach", "location": "Nottingham / UK", "format": "Online and in-person", "age_range": "Check programme", "cost": "Free / check programme", "subjects": "Medicine, Veterinary Science, General / All Sectors", "link": "https://www.nottingham.ac.uk/support-services/home/widening-participation-and-outreach/our-programmes.html", "description": "Nottingham's official widening-participation programme hub, with pathways, summer schools and university-application support."},
    {"title": "University of Liverpool widening participation and outreach", "provider": "University of Liverpool", "category": "Academic", "activity_type": "University Outreach", "location": "Liverpool / UK", "format": "Online and in-person", "age_range": "Key Stage 3-5 / check programme", "cost": "Free / check programme", "subjects": "Medicine, Health, General / All Sectors", "link": "https://www.liverpool.ac.uk/study/widening-participation/", "description": "Liverpool's official widening-participation and outreach hub, including academic mentoring, access programmes and post-16 support."},
    {"title": "University of York widening access", "provider": "University of York", "category": "Academic", "activity_type": "University Outreach", "location": "York / UK", "format": "Online and in-person", "age_range": "Pre-16 and post-16 / check programme", "cost": "Free / check programme", "subjects": "General / All Sectors", "link": "https://www.york.ac.uk/schools-and-colleges/widening-access/", "description": "York's official widening-access hub with pre-16 and post-16 activities, talks, campus visits and support for prospective students."},
    {"title": "Forage virtual job simulations", "provider": "Forage", "category": "Careers", "activity_type": "Virtual Work Experience", "location": "International / online", "format": "Online", "age_range": "Check provider eligibility", "cost": "Free", "subjects": "Business, Technology, Law, Finance", "link": "https://www.theforage.com/", "description": "Free employer-designed virtual job simulations. Browse current programmes and complete one at your own pace; availability and eligibility are shown by the provider."},
    {"title": "Springpod virtual work experience", "provider": "Springpod", "category": "Careers", "activity_type": "Virtual Work Experience", "location": "UK / online", "format": "Online", "age_range": "Check provider eligibility", "cost": "Free / check provider", "subjects": "Medicine, Business, Law, Technology, Engineering", "link": "https://www.springpod.com/virtual-work-experience", "description": "Browse current virtual work-experience programmes and provider eligibility directly with Springpod."},
    {"title": "Speakers for Schools work experience", "provider": "Speakers for Schools", "category": "Careers", "activity_type": "Work Experience", "location": "UK", "format": "Online and in-person", "age_range": "Check provider eligibility", "cost": "Free", "subjects": "General / All Sectors", "link": "https://www.speakersforschools.org/experience/", "description": "Current work-experience opportunities for young people. Check the provider page for open placements, dates and eligibility."},
    {"title": "Nuffield Research Placements", "provider": "Nuffield Foundation", "category": "Academic", "activity_type": "Research", "location": "UK", "format": "In-person and hybrid", "age_range": "Post-16 / check provider", "cost": "Free", "subjects": "Science, Research & Sustainability", "link": "https://www.nuffieldresearchplacements.org/", "description": "Research placements for eligible post-16 students. Check regional availability, timetable and application criteria on the official page."},
    {"title": "FutureLearn short courses and certificates", "provider": "FutureLearn", "category": "Academic", "activity_type": "Course / Programme", "location": "International / online", "format": "Online", "age_range": "Check provider eligibility", "cost": "Free and paid options", "subjects": "General / All Sectors", "link": "https://www.futurelearn.com/courses", "description": "Explore current online short courses from universities and cultural institutions. Course access and certificate options vary."},
    {"title": "OpenLearn free courses", "provider": "The Open University", "category": "Academic", "activity_type": "Course / Programme", "location": "International / online", "format": "Online", "age_range": "Open access / check course", "cost": "Free", "subjects": "General / All Sectors", "link": "https://www.open.edu/openlearn/free-courses", "description": "Free online courses across subjects. Check individual course pages for study time and digital badges."},
    {"title": "National Saturday Club", "provider": "National Saturday Club", "category": "Creative", "activity_type": "Course / Programme", "location": "UK", "format": "In-person", "age_range": "13-16", "cost": "Free", "subjects": "Art, Design, Technology", "link": "https://www.nationalsaturdayclub.org/", "description": "Saturday clubs in art, design, science, technology and performance. Check local club availability and current application details."},
    {"title": "Duke of Edinburgh's Award", "provider": "DofE", "category": "Leadership", "activity_type": "Leadership Programme", "location": "International", "format": "In-person and hybrid", "age_range": "14+", "cost": "Check provider", "subjects": "Leadership, Volunteering, Sport", "link": "https://www.dofe.org/", "description": "Structured volunteering, physical, skills and expedition challenges. Check local centre availability and participation costs."},
    {"title": "Do-it volunteering opportunities", "provider": "Do-it", "category": "Volunteering", "activity_type": "Volunteering", "location": "UK", "format": "Online and in-person", "age_range": "Check organisation eligibility", "cost": "Free", "subjects": "General / All Sectors", "link": "https://doit.life/", "description": "Search current volunteering roles by location and cause. Each organisation sets its own age and safeguarding requirements."},
    {"title": "British Science Association CREST Awards", "provider": "British Science Association", "category": "Academic", "activity_type": "Research", "location": "UK and international", "format": "Online and in-person", "age_range": "11-19", "cost": "Check provider", "subjects": "Science, Research & Sustainability", "link": "https://www.crestawards.org/", "description": "Student-led STEM project awards. Check current project formats, costs and school participation guidance."},
    {"title": "UK Mathematics Trust competitions", "provider": "UK Mathematics Trust", "category": "Academic", "activity_type": "Competition", "location": "UK", "format": "School-based", "age_range": "Check competition", "cost": "Check school / provider", "subjects": "Mathematics", "link": "https://ukmt.org.uk/competitions", "description": "Current mathematics challenges, olympiads and team competitions. Check the relevant competition’s year-group and entry details."},
    {"title": "Erasmus+ Youth opportunities", "provider": "European Youth Portal", "category": "International", "activity_type": "International Programme", "location": "International", "format": "Online and in-person", "age_range": "Check opportunity", "cost": "Varies", "subjects": "Languages, Leadership, Volunteering", "link": "https://youth.europa.eu/go-abroad_en", "description": "Explore current international youth exchanges, volunteering and mobility opportunities. Eligibility depends on residence, age and host programme."},
    {"title": "WorkingAbroad volunteer projects and internships", "provider": "WorkingAbroad", "category": "International", "activity_type": "International Volunteering", "location": "International", "format": "In-person", "age_range": "Under 18, student and adult options — check project", "cost": "Paid / check project", "subjects": "Environment, Wildlife Conservation, Marine Science, Community Development", "link": "https://www.workingabroad.com/", "description": "Search international conservation, community-volunteering and internship projects. WorkingAbroad includes student and under-18 options, but each project has its own age, cost, travel and safeguarding requirements."},
    {"title": "LTA junior tennis competitions", "provider": "LTA", "category": "Sport", "activity_type": "Competition", "location": "UK", "format": "In-person", "age_range": "Junior / check event", "cost": "Check event", "subjects": "Tennis, Sport", "link": "https://www.lta.org.uk/compete/junior/", "description": "Official LTA hub for junior tennis competition, from beginner matchplay and local tournaments to county and national pathways. Find current events and age eligibility."},
    {"title": "LTA youth tennis leadership and volunteering", "provider": "LTA", "category": "Sport", "activity_type": "Leadership Programme", "location": "UK", "format": "In-person and hybrid", "age_range": "11-18", "cost": "Free / check local delivery", "subjects": "Tennis, Sport, Leadership, Volunteering", "link": "https://www.lta.org.uk/roles-and-venues/volunteers/become-a-tennis-volunteer/", "description": "LTA's official tennis-volunteering guide, including LTA Youth Tennis Leaders for 11-18-year-olds, local competition volunteering and leadership pathways."},
    {"title": "Badminton England competitions", "provider": "Badminton England", "category": "Sport", "activity_type": "Competition", "location": "England / UK", "format": "In-person", "age_range": "Junior / check tournament", "cost": "Check tournament", "subjects": "Badminton, Sport", "link": "https://www.badmintonengland.co.uk/competition/", "description": "Official Badminton England competition hub. Use the tournament system to find current junior, club and national badminton competitions."},
    {"title": "Badminton England volunteering", "provider": "Badminton England", "category": "Sport", "activity_type": "Volunteering", "location": "England / UK", "format": "In-person", "age_range": "Check role", "cost": "Free", "subjects": "Badminton, Sport, Leadership", "link": "https://www.badmintonengland.co.uk/volunteers/", "description": "Official Badminton England volunteering information and routes to major-event, club and competition volunteering. Check individual role age requirements."},
    {"title": "Badminton England club and junior session finder", "provider": "Badminton England", "category": "Sport", "activity_type": "Sport Programme", "location": "England / UK", "format": "In-person", "age_range": "Juniors / check session", "cost": "Free and paid options", "subjects": "Badminton, Sport", "link": "https://www.badmintonengland.co.uk/play/", "description": "Find affiliated badminton clubs, junior sessions and official participation programmes. Local sessions set their own age, price and booking details."},
    {"title": "Powerleague local football leagues", "provider": "Powerleague", "category": "Sport", "activity_type": "Sport Programme", "location": "UK", "format": "In-person", "age_range": "Check venue", "cost": "Check venue", "subjects": "Football, Sport", "link": "https://www.powerleague.co.uk/", "description": "Find local small-sided football leagues and venues. Check each venue for youth availability, team entry rules and current prices."},
    {"title": "School Games sport, competition and leadership", "provider": "School Games", "category": "Sport", "activity_type": "Competition", "location": "England / UK", "format": "School-based and in-person", "age_range": "School age", "cost": "Free through participating schools", "subjects": "Multi-sport, Sport, Leadership", "link": "https://www.yourschoolgames.com/", "description": "Official School Games hub for school sport, local competitions, youth leadership and volunteering. Ask your school or School Games Organiser about local activity."},
    {"title": "Youth Sport Trust young leader training", "provider": "Youth Sport Trust", "category": "Sport", "activity_type": "Leadership Programme", "location": "England / UK", "format": "School-based", "age_range": "11-14", "cost": "Free through schools", "subjects": "Sport, Leadership", "link": "https://www.youthsporttrust.org/young-leader-training", "description": "Free young-leader training resources that help secondary pupils plan, lead and review inclusive physical activity in school. Delivered by a school or youth-sport leader."},
    {"title": "London Youth Games Open Games", "provider": "London Youth Games", "category": "Sport", "activity_type": "Competition", "location": "London", "format": "In-person", "age_range": "7-17 / check sport", "cost": "Free / check borough", "subjects": "Multi-sport, Sport", "link": "https://www.londonyouthgames.org/open-games-how-to-compete/", "description": "Europe's largest community youth sporting competition across 37 sports. Open to young people who live or attend school in a London borough; register through your Borough Team Organiser."},
    {"title": "London Youth Games GamesForce volunteering", "provider": "London Youth Games", "category": "Sport", "activity_type": "Volunteering", "location": "London", "format": "In-person", "age_range": "14+ / check role", "cost": "Free", "subjects": "Multi-sport, Sport, Leadership, Media", "link": "https://www.londonyouthgames.org/volunteer/", "description": "Volunteer in sport, event delivery, media or officiating with London Youth Games. GamesForce Teams welcomes young leaders aged 14+ through schools, colleges and universities."},
    {"title": "England Netball National Schools Competition", "provider": "England Netball", "category": "Sport", "activity_type": "Competition", "location": "England", "format": "School-based and in-person", "age_range": "Under 14, Under 16 and Under 19", "cost": "Check school membership", "subjects": "Netball, Sport", "link": "https://www.englandnetball.co.uk/national-schools-competition/how-to-join/", "description": "England Netball's National Schools Competition for U14, U16 and U19 teams. Ask your school sports department or local County Netball Association about entry."},
    {"title": "England Netball competitions", "provider": "England Netball", "category": "Sport", "activity_type": "Competition", "location": "England", "format": "In-person", "age_range": "Junior and youth / check competition", "cost": "Check competition", "subjects": "Netball, Sport", "link": "https://www.englandnetball.co.uk/competitions/npl/", "description": "Official England Netball competition hub, including national schools, U14, U16, U17 and U19 competition pathways. Check selection and team-entry requirements."},
    {"title": "England Athletics youth competition pathways", "provider": "England Athletics", "category": "Sport", "activity_type": "Competition", "location": "England", "format": "In-person", "age_range": "Under 10-20 / check event", "cost": "Check event", "subjects": "Athletics, Sport", "link": "https://www.englandathletics.org/news/competition-opportunities-for-u10s-and-u12s/", "description": "Official England Athletics overview of youth competition routes, including local team events and Youth Development League pathways for U14-U20 athletes."},
    {"title": "England Rugby women and girls playing opportunities", "provider": "Rugby Football Union", "category": "Sport", "activity_type": "Sport Programme", "location": "England", "format": "In-person", "age_range": "Age grade / check club", "cost": "Check club", "subjects": "Rugby, Sport", "link": "https://www.englandrugby.com/run/coaching/women-and-girls/playing-and-competing", "description": "Official RFU guide to girls' and women’s age-grade rugby, including club festivals, fixtures, training and recruitment camps. Check local club opportunities."},
    {"title": "Durham University Access and Engagement", "provider": "Durham University", "category": "Academic", "activity_type": "University Outreach", "location": "Durham / UK", "format": "Online and in-person", "age_range": "Check programme", "cost": "Free / check programme", "subjects": "General / All Sectors", "link": "https://dur.ac.uk/visit-us/schools/access-engagement/", "description": "Official Durham access programmes, summer schools and school engagement opportunities."},
    {"title": "Newcastle University Schools and Outreach", "provider": "Newcastle University", "category": "Academic", "activity_type": "University Outreach", "location": "Newcastle / UK", "format": "Online and in-person", "age_range": "Check programme", "cost": "Free / check programme", "subjects": "General / All Sectors", "link": "https://www.ncl.ac.uk/schools/", "description": "Official Newcastle subject activities, events, PARTNERS and outreach opportunities."},
    {"title": "University of Bath Widening Access Outreach", "provider": "University of Bath", "category": "Academic", "activity_type": "University Outreach", "location": "Bath / UK", "format": "Online and in-person", "age_range": "Check programme", "cost": "Free / check programme", "subjects": "General / All Sectors", "link": "https://www.bath.ac.uk/campaigns/widening-access-outreach/", "description": "Official Bath outreach hub including programmes, summer schools, work experience and online opportunities."},
    {"title": "Lancaster University Widening Participation", "provider": "Lancaster University", "category": "Academic", "activity_type": "University Outreach", "location": "Lancaster / UK", "format": "Online and in-person", "age_range": "Check programme", "cost": "Free / check programme", "subjects": "Medicine, General / All Sectors", "link": "https://www.lancaster.ac.uk/widening-participation/", "description": "Official Lancaster access programmes, medicine access and school activities."},
    {"title": "University of Southampton Schools and Colleges", "provider": "University of Southampton", "category": "Academic", "activity_type": "University Outreach", "location": "Southampton / UK", "format": "Online and in-person", "age_range": "Check programme", "cost": "Free / check programme", "subjects": "General / All Sectors", "link": "https://www.southampton.ac.uk/schools-colleges", "description": "Official Southampton summer schools, pre- and post-16 programmes and university preparation."},
    {"title": "Cardiff University Widening Participation", "provider": "Cardiff University", "category": "Academic", "activity_type": "University Outreach", "location": "Cardiff / UK", "format": "Online and in-person", "age_range": "Check programme", "cost": "Free / check programme", "subjects": "General / All Sectors", "link": "https://www.cardiff.ac.uk/about/our-profile/who-we-are/widening-participation", "description": "Official Cardiff widening-participation programmes and outreach support."},
    {"title": "University of Surrey Schools and Colleges", "provider": "University of Surrey", "category": "Academic", "activity_type": "University Outreach", "location": "Guildford / UK", "format": "Online and in-person", "age_range": "Check programme", "cost": "Free / check programme", "subjects": "General / All Sectors", "link": "https://www.surrey.ac.uk/schools-colleges", "description": "Official Surrey school and college outreach information and activities."},
    {"title": "University of Leicester Schools and Colleges", "provider": "University of Leicester", "category": "Academic", "activity_type": "University Outreach", "location": "Leicester / UK", "format": "Online and in-person", "age_range": "Check programme", "cost": "Free / check programme", "subjects": "General / All Sectors", "link": "https://le.ac.uk/study/schools-and-colleges", "description": "Official Leicester schools and colleges opportunities and outreach."},
    {"title": "University of East Anglia Young People", "provider": "University of East Anglia", "category": "Academic", "activity_type": "University Outreach", "location": "Norwich / UK", "format": "Online and in-person", "age_range": "Check programme", "cost": "Free / check programme", "subjects": "General / All Sectors", "link": "https://www.uea.ac.uk/study/information-for/young-people", "description": "Official UEA information and opportunities for young people."},
    {"title": "University of Essex Schools and Colleges", "provider": "University of Essex", "category": "Academic", "activity_type": "University Outreach", "location": "Essex / UK", "format": "Online and in-person", "age_range": "Check programme", "cost": "Free / check programme", "subjects": "General / All Sectors", "link": "https://www.essex.ac.uk/schools-and-colleges", "description": "Official Essex schools and colleges outreach activity."},
    {"title": "University of Kent Schools and Colleges", "provider": "University of Kent", "category": "Academic", "activity_type": "University Outreach", "location": "Kent / UK", "format": "Online and in-person", "age_range": "Check programme", "cost": "Free / check programme", "subjects": "General / All Sectors", "link": "https://www.kent.ac.uk/schools-and-colleges", "description": "Official Kent school and college outreach programmes."},
    {"title": "Loughborough University School and College Liaison", "provider": "Loughborough University", "category": "Academic", "activity_type": "University Outreach", "location": "Loughborough / UK", "format": "Online and in-person", "age_range": "Check programme", "cost": "Free / check programme", "subjects": "Sport, Engineering, General / All Sectors", "link": "https://www.lboro.ac.uk/study/school-college-liaison/", "description": "Official Loughborough school and college liaison activities."},
    {"title": "University of Glasgow Widening Participation", "provider": "University of Glasgow", "category": "Academic", "activity_type": "University Outreach", "location": "Glasgow / UK", "format": "Online and in-person", "age_range": "Check programme", "cost": "Free / check programme", "subjects": "General / All Sectors", "link": "https://www.gla.ac.uk/study/wp/", "description": "Official Glasgow widening-participation opportunities and support."},
    {"title": "University of St Andrews Widening Access", "provider": "University of St Andrews", "category": "Academic", "activity_type": "University Outreach", "location": "St Andrews / UK", "format": "Online and in-person", "age_range": "Check programme", "cost": "Free / check programme", "subjects": "General / All Sectors", "link": "https://www.st-andrews.ac.uk/study/access/", "description": "Official St Andrews widening-access programmes and guidance."},
    {"title": "Queen's University Belfast Widening Participation", "provider": "Queen's University Belfast", "category": "Academic", "activity_type": "University Outreach", "location": "Belfast / UK", "format": "Online and in-person", "age_range": "Check programme", "cost": "Free / check programme", "subjects": "General / All Sectors", "link": "https://www.qub.ac.uk/directorates/sgc/wpu/", "description": "Official Queen's Belfast widening-participation opportunities."},
    {"title": "University of Strathclyde Widening Access", "provider": "University of Strathclyde", "category": "Academic", "activity_type": "University Outreach", "location": "Glasgow / UK", "format": "Online and in-person", "age_range": "Check programme", "cost": "Free / check programme", "subjects": "General / All Sectors", "link": "https://www.strath.ac.uk/studywithus/wideningaccess/", "description": "Official Strathclyde widening-access activities and guidance."},
    {"title": "Royal Society of Chemistry Enrichment", "provider": "Royal Society of Chemistry", "category": "Academic", "activity_type": "Competition", "location": "UK", "format": "School-based and online", "age_range": "Check competition", "cost": "Check provider", "subjects": "Chemistry, Science", "link": "https://edu.rsc.org/enrichment", "description": "Official chemistry enrichment hub including Olympiad, Top of the Bench and Schools' Analyst."},
    {"title": "UK Chemistry Olympiad", "provider": "Royal Society of Chemistry", "category": "Academic", "activity_type": "Olympiad", "location": "UK", "format": "School-based", "age_range": "Post-16 / check cycle", "cost": "Check school", "subjects": "Chemistry, Science", "link": "https://edu.rsc.org/enrichment/uk-chemistry-olympiad", "description": "Official UK Chemistry Olympiad page with current competition-cycle details."},
    {"title": "Royal Society of Biology Awards and Competitions", "provider": "Royal Society of Biology", "category": "Academic", "activity_type": "Competition", "location": "UK", "format": "School-based and online", "age_range": "Check competition", "cost": "Check provider", "subjects": "Biology, Science", "link": "https://www.rsb.org.uk/awards-and-competitions.html", "description": "Official biology awards and competitions hub."},
    {"title": "British Biology Olympiad", "provider": "UK Biology Competitions", "category": "Academic", "activity_type": "Olympiad", "location": "UK", "format": "School-based", "age_range": "Post-16 / check cycle", "cost": "Check school", "subjects": "Biology, Science", "link": "https://ukbiologycompetitions.org/british-biology-olympiad/", "description": "Official British Biology Olympiad competition page."},
    {"title": "Intermediate Biology Olympiad", "provider": "UK Biology Competitions", "category": "Academic", "activity_type": "Olympiad", "location": "UK", "format": "School-based", "age_range": "Check cycle", "cost": "Check school", "subjects": "Biology, Science", "link": "https://ukbiologycompetitions.org/intermediate-biology-olympiad/", "description": "Official Intermediate Biology Olympiad page."},
    {"title": "Biology Challenge", "provider": "UK Biology Competitions", "category": "Academic", "activity_type": "Competition", "location": "UK", "format": "School-based", "age_range": "Check cycle", "cost": "Check school", "subjects": "Biology, Science", "link": "https://ukbiologycompetitions.org/biology-challenge/", "description": "Official Biology Challenge competition page."},
    {"title": "British Physics Olympiad", "provider": "British Physics Olympiad", "category": "Academic", "activity_type": "Olympiad", "location": "UK", "format": "School-based", "age_range": "Check cycle", "cost": "Check school", "subjects": "Physics, Science", "link": "https://www.bpho.org.uk/", "description": "Official British Physics Olympiad hub."},
    {"title": "Isaac Physics", "provider": "Isaac Physics", "category": "Academic", "activity_type": "Course / Programme", "location": "UK and international", "format": "Online", "age_range": "Check provider", "cost": "Free", "subjects": "Physics, Mathematics", "link": "https://isaacphysics.org/", "description": "Free official physics problem-solving, enrichment and preparation platform."},
    {"title": "British Informatics Olympiad", "provider": "British Informatics Olympiad", "category": "Academic", "activity_type": "Olympiad", "location": "UK", "format": "School-based and online", "age_range": "Check cycle", "cost": "Check school", "subjects": "Computer Science, Mathematics", "link": "https://www.olympiad.org.uk/", "description": "Official British Informatics Olympiad hub."},
    {"title": "UK Bebras Challenge", "provider": "UK Bebras", "category": "Academic", "activity_type": "Competition", "location": "UK", "format": "School-based", "age_range": "School age", "cost": "Free / check school", "subjects": "Computer Science, Mathematics", "link": "https://www.bebras.uk/", "description": "Official UK Bebras computational-thinking challenge."},
    {"title": "Arkwright Engineering Scholarships", "provider": "Arkwright Engineering Scholarships", "category": "Academic", "activity_type": "Scholarship", "location": "UK", "format": "School-based", "age_range": "Check cycle", "cost": "Free", "subjects": "Engineering, Technology", "link": "https://www.arkwright.org.uk/", "description": "Official engineering scholarship and mentoring programme."},
    {"title": "Engineering Development Trust", "provider": "Engineering Development Trust", "category": "Academic", "activity_type": "Course / Programme", "location": "UK", "format": "Online and in-person", "age_range": "Check programme", "cost": "Free and paid options", "subjects": "Engineering, Technology, Science", "link": "https://www.etrust.org.uk/", "description": "Official Engineering Development Trust programmes and STEM enrichment."},
    {"title": "STEM Learning Secondary Enrichment", "provider": "STEM Learning", "category": "Academic", "activity_type": "Course / Programme", "location": "UK", "format": "Online and in-person", "age_range": "Secondary school", "cost": "Free / check programme", "subjects": "STEM, Science, Technology", "link": "https://www.stem.org.uk/secondary/enrichment", "description": "Official STEM Learning enrichment activities for secondary students."},
    {"title": "IET Education", "provider": "Institution of Engineering and Technology", "category": "Academic", "activity_type": "Course / Programme", "location": "UK", "format": "Online and in-person", "age_range": "Check programme", "cost": "Free / check programme", "subjects": "Engineering, Technology", "link": "https://education.theiet.org/", "description": "Official IET engineering and technology education opportunities."},
    {"title": "Tomorrow's Engineers", "provider": "Tomorrow's Engineers", "category": "Careers", "activity_type": "Careers Programme", "location": "UK", "format": "Online and in-person", "age_range": "Check programme", "cost": "Free", "subjects": "Engineering, Technology", "link": "https://www.tomorrowsengineers.org.uk/", "description": "Engineering careers and student opportunity hub."},
    {"title": "CyberFirst", "provider": "National Cyber Security Centre", "category": "Academic", "activity_type": "Course / Programme", "location": "UK", "format": "Online and in-person", "age_range": "Check programme", "cost": "Free", "subjects": "Computer Science, Cyber Security", "link": "https://www.ncsc.gov.uk/cyberfirst/overview", "description": "Official NCSC CyberFirst courses, competitions and cyber pathways."},
    {"title": "Oxford Economics Society Essay Competition", "provider": "Oxford Economics Society", "category": "Academic", "activity_type": "Essay Competition", "location": "UK and international", "format": "Online", "age_range": "Sixth form / check cycle", "cost": "Free", "subjects": "Economics", "link": "https://oxfordeconsoc.squarespace.com/essay-competition", "description": "Economics essay competition with current questions and entry details."},
    {"title": "FCDO Next Generation Economics Competition", "provider": "Foreign, Commonwealth and Development Office", "category": "Academic", "activity_type": "Essay Competition", "location": "UK", "format": "Online", "age_range": "14-18 / check cycle", "cost": "Free", "subjects": "Economics, Politics", "link": "https://www.gov.uk/guidance/fcdo-next-generation-economics-competition", "description": "Official FCDO Next Generation Economics Competition page."},
    {"title": "Bank of England Student Competitions", "provider": "Bank of England", "category": "Academic", "activity_type": "Competition", "location": "UK", "format": "Online and in-person", "age_range": "Check competition", "cost": "Free", "subjects": "Economics, Finance", "link": "https://www.bankofengland.co.uk/education/competitions", "description": "Official Bank of England student competition page."},
    {"title": "Young Enterprise Programmes", "provider": "Young Enterprise", "category": "Leadership", "activity_type": "Leadership Programme", "location": "UK", "format": "School-based and in-person", "age_range": "Check programme", "cost": "Check school", "subjects": "Business, Finance, Entrepreneurship", "link": "https://www.young-enterprise.org.uk/what-we-do/our-programmes", "description": "Official enterprise, finance and work-readiness programmes."},
    {"title": "Institute of Economic Affairs Student Resources", "provider": "Institute of Economic Affairs", "category": "Academic", "activity_type": "Course / Programme", "location": "UK", "format": "Online and in-person", "age_range": "Check programme", "cost": "Free / check programme", "subjects": "Economics, Politics", "link": "https://iea.org.uk/students/", "description": "Economics student resources, events and opportunities."},
    {"title": "Young Citizens Mock Trials", "provider": "Young Citizens", "category": "Academic", "activity_type": "Competition", "location": "UK", "format": "In-person and school-based", "age_range": "Check competition", "cost": "Check school", "subjects": "Law, Politics", "link": "https://www.youngcitizens.org/programmes/mock-trials/", "description": "Official Bar and Magistrates' Court mock-trial competitions."},
    {"title": "Historical Association Student Competitions", "provider": "Historical Association", "category": "Academic", "activity_type": "Competition", "location": "UK", "format": "Online and in-person", "age_range": "Check competition", "cost": "Check provider", "subjects": "History", "link": "https://www.history.org.uk/student/categories/student-competitions", "description": "Official history student competitions including Great Debate and Young Historian."},
    {"title": "Royal Geographical Society School Competitions", "provider": "Royal Geographical Society", "category": "Academic", "activity_type": "Competition", "location": "UK", "format": "Online and in-person", "age_range": "Check competition", "cost": "Check provider", "subjects": "Geography", "link": "https://www.rgs.org/schools/competitions", "description": "Official geography competitions and school awards."},
    {"title": "Royal Geographical Society School Events", "provider": "Royal Geographical Society", "category": "Academic", "activity_type": "Event", "location": "UK", "format": "Online and in-person", "age_range": "Check event", "cost": "Check event", "subjects": "Geography", "link": "https://www.rgs.org/schools", "description": "Official geography school events, lectures, study days, fieldwork and careers activity."},
    {"title": "Sidgwick Prize", "provider": "Sidgwick Prize", "category": "Academic", "activity_type": "Essay Competition", "location": "UK and international", "format": "Online", "age_range": "Check cycle", "cost": "Free", "subjects": "Philosophy, Politics, Economics, History, Law, Psychology", "link": "https://www.sidgwickprize.com/", "description": "Interdisciplinary essay competition covering humanities and social sciences."},
    {"title": "John Locke Institute Essay Competition", "provider": "John Locke Institute", "category": "Academic", "activity_type": "Essay Competition", "location": "International", "format": "Online", "age_range": "Check cycle", "cost": "Free / check cycle", "subjects": "Economics, Law, Politics, History, Philosophy", "link": "https://www.johnlockeinstitute.com/essay-competition", "description": "Official John Locke Institute essay competition page."},
    {"title": "Immerse Education Essay Competition", "provider": "Immerse Education", "category": "Academic", "activity_type": "Essay Competition", "location": "International", "format": "Online", "age_range": "Check cycle", "cost": "Free", "subjects": "General / All Sectors", "link": "https://www.immerse.education/essay-competition/", "description": "Official Immerse Education essay competition information."},
    {"title": "Medic Mentor", "provider": "Medic Mentor", "category": "Careers", "activity_type": "Course / Programme", "location": "UK", "format": "Online and in-person", "age_range": "Check programme", "cost": "Free and paid options", "subjects": "Medicine, Health", "link": "https://medicmentor.org/", "description": "Medical careers mentoring, conferences and student opportunities."},
    {"title": "NHS Health Careers", "provider": "NHS", "category": "Careers", "activity_type": "Careers Programme", "location": "UK", "format": "Online", "age_range": "Check opportunity", "cost": "Free", "subjects": "Medicine, Health", "link": "https://www.healthcareers.nhs.uk/", "description": "Official NHS careers information and healthcare exploration resources."},
    {"title": "Brighton and Sussex Medical School Virtual Work Experience", "provider": "Brighton and Sussex Medical School", "category": "Careers", "activity_type": "Virtual Work Experience", "location": "UK / online", "format": "Online", "age_range": "Check provider", "cost": "Free", "subjects": "Medicine, Health", "link": "https://bsmsoutreach.thinkific.com/", "description": "Official BSMS virtual work-experience learning platform."},
    {"title": "Lancaster Medical School Outreach", "provider": "Lancaster Medical School", "category": "Academic", "activity_type": "University Outreach", "location": "Lancaster / UK", "format": "Online and in-person", "age_range": "Check programme", "cost": "Free / check programme", "subjects": "Medicine, Health", "link": "https://www.lancaster.ac.uk/lms/about-us/widening-participation/", "description": "Official Lancaster Medical School widening-participation outreach."},
    {"title": "British Red Cross Young People Opportunities", "provider": "British Red Cross", "category": "Volunteering", "activity_type": "Volunteering", "location": "UK", "format": "Online and in-person", "age_range": "15+ / check role", "cost": "Free", "subjects": "Volunteering, Health, Leadership", "link": "https://www.redcross.org.uk/get-involved/opportunities-for-young-people", "description": "Official young-person volunteering, work-experience, placement and DofE opportunities."},
    {"title": "British Red Cross Youth Volunteer Placements", "provider": "British Red Cross", "category": "Volunteering", "activity_type": "Volunteering", "location": "UK", "format": "In-person", "age_range": "Check role", "cost": "Free", "subjects": "Volunteering, Health, Leadership", "link": "https://www.redcross.org.uk/get-involved/volunteer/youth-volunteer-placements", "description": "Official British Red Cross youth volunteer-placement listings."},
    {"title": "RSPB Youth Groups", "provider": "RSPB", "category": "Volunteering", "activity_type": "Volunteering", "location": "UK", "format": "In-person", "age_range": "Check group", "cost": "Check group", "subjects": "Environment, Biology, Volunteering", "link": "https://www.rspb.org.uk/helping-nature/what-you-can-do/inspiring-young-people-to-take-action-for-nature/youth-groups", "description": "Official RSPB youth groups, local wildlife activity and environmental action."},
    {"title": "RSPB Find a Youth Group", "provider": "RSPB", "category": "Volunteering", "activity_type": "Volunteering", "location": "UK", "format": "In-person", "age_range": "Check group", "cost": "Check group", "subjects": "Environment, Biology, Volunteering", "link": "https://www.rspb.org.uk/helping-nature/what-you-can-do/inspiring-young-people-to-take-action-for-nature/find-a-local-youth-group", "description": "Official RSPB regional youth-group finder."},
    {"title": "The Wildlife Trusts Volunteering", "provider": "The Wildlife Trusts", "category": "Volunteering", "activity_type": "Volunteering", "location": "UK", "format": "In-person", "age_range": "Check role", "cost": "Free", "subjects": "Environment, Biology, Volunteering", "link": "https://www.wildlifetrusts.org/volunteering-opportunities", "description": "Official Wildlife Trusts volunteering opportunities."},
    {"title": "National Trust Volunteering", "provider": "National Trust", "category": "Volunteering", "activity_type": "Volunteering", "location": "UK", "format": "In-person", "age_range": "Check role", "cost": "Free", "subjects": "Environment, History, Volunteering", "link": "https://www.nationaltrust.org.uk/support-us/volunteer", "description": "Official National Trust volunteering opportunities."},
    {"title": "Foyle Young Poets of the Year", "provider": "The Poetry Society", "category": "Creative", "activity_type": "Competition", "location": "UK and international", "format": "Online", "age_range": "11-17", "cost": "Free", "subjects": "Writing, English", "link": "https://foyleyoungpoets.org/", "description": "Major free poetry competition for young people aged 11-17."},
    {"title": "V&A Young People", "provider": "Victoria and Albert Museum", "category": "Creative", "activity_type": "Course / Programme", "location": "London / UK", "format": "Online and in-person", "age_range": "Check programme", "cost": "Free / check programme", "subjects": "Art, Design, Creative", "link": "https://www.vam.ac.uk/info/young-people", "description": "Official V&A workshops, courses, events and Youth Collective opportunities."},
    {"title": "British Museum Young People", "provider": "British Museum", "category": "Creative", "activity_type": "Course / Programme", "location": "London / UK", "format": "Online and in-person", "age_range": "Check programme", "cost": "Free / check programme", "subjects": "History, Art, Creative", "link": "https://www.britishmuseum.org/learn/young-people", "description": "Official British Museum young-person programmes and digital opportunities."},
    {"title": "National Theatre Young People", "provider": "National Theatre", "category": "Creative", "activity_type": "Course / Programme", "location": "London / UK", "format": "Online and in-person", "age_range": "Check programme", "cost": "Free / check programme", "subjects": "Drama, Theatre, Creative", "link": "https://www.nationaltheatre.org.uk/learn-explore/young-people/", "description": "Official National Theatre young-person programmes and creative opportunities."},
    {"title": "BFI Young People and Film Academy", "provider": "British Film Institute", "category": "Creative", "activity_type": "Course / Programme", "location": "UK", "format": "Online and in-person", "age_range": "Check programme", "cost": "Free / check programme", "subjects": "Film, Media, Creative", "link": "https://www.bfi.org.uk/bfi-film-academy-opportunities-young-creatives", "description": "Official BFI Film Academy and young-creative opportunities."},
]

def additional_source(title, provider, category, activity_type, subjects, link, description, location="UK", format="Online and in-person", age_range="Check provider", cost="Free / check programme"):
    return {"title": title, "provider": provider, "category": category, "activity_type": activity_type, "location": location, "format": format, "age_range": age_range, "cost": cost, "subjects": subjects, "link": link, "description": description}


# Additional direct official pages supplied for the ongoing curated-source expansion.
SOURCES.extend([
    additional_source("Oxford Academic Competitions Hub", "University of Oxford", "Academic", "Competition", "General / All Sectors", "https://www.ox.ac.uk/admissions/undergraduate/supercurricular-hub/academic-competitions-for-school-aged-students", "Oxford's official hub for academic competitions for school-aged students."),
    additional_source("St Edmund Hall Big Think Competition", "University of Oxford", "Academic", "Essay Competition", "General / All Sectors", "https://www.seh.ox.ac.uk/study/outreach/events-and-competitions/big-think-competition", "Official Oxford college Big Think competition details."),
    additional_source("St Hugh's Oxford Essay Competitions", "University of Oxford", "Academic", "Essay Competition", "General / All Sectors", "https://www.st-hughs.ox.ac.uk/prospective-students/outreach-at-st-hughs/essay-competitions/", "Official St Hugh's essay-competition page."),
    additional_source("Oxford UNIQ", "University of Oxford", "Academic", "University Outreach", "General / All Sectors", "https://www.uniq.ox.ac.uk/", "Official Oxford UNIQ access programme."),
    additional_source("Oxford Mathematics Outreach", "University of Oxford", "Academic", "University Outreach", "Mathematics", "https://www.maths.ox.ac.uk/study-here/undergraduate-study/outreach", "Official Oxford Mathematics outreach activity."),
    additional_source("Oxford Physics Schools Engagement", "University of Oxford", "Academic", "University Outreach", "Physics, Science", "https://www.physics.ox.ac.uk/engage/schools", "Official Oxford Physics school engagement."),
    additional_source("Oxford Chemistry Outreach", "University of Oxford", "Academic", "University Outreach", "Chemistry, Science", "https://www.chem.ox.ac.uk/outreach", "Official Oxford Chemistry outreach."),
    additional_source("Oxford Computer Science Outreach", "University of Oxford", "Academic", "University Outreach", "Computer Science", "https://www.cs.ox.ac.uk/admissions/undergraduate/why_oxford/outreach.html", "Official Oxford Computer Science outreach."),
    additional_source("Oxford Classics Outreach", "University of Oxford", "Academic", "University Outreach", "Classics, History", "https://www.classics.ox.ac.uk/outreach", "Official Oxford Classics outreach."),
    additional_source("Oxford History Schools and Outreach", "University of Oxford", "Academic", "University Outreach", "History", "https://www.history.ox.ac.uk/schools-and-outreach", "Official Oxford History school and outreach activity."),
    additional_source("Cambridge Queens' College Competitions", "University of Cambridge", "Academic", "Competition", "General / All Sectors", "https://www.queens.cam.ac.uk/applying-here/access-and-outreach/competitions/", "Official Cambridge college competitions."),
    additional_source("Cambridge Christ's College Outreach", "University of Cambridge", "Academic", "University Outreach", "General / All Sectors", "https://www.christs.cam.ac.uk/admissions/outreach-access-and-schools-liaison", "Official Christ's College outreach and schools liaison."),
    additional_source("Cambridge Trinity College Access", "University of Cambridge", "Academic", "University Outreach", "General / All Sectors", "https://www.trin.cam.ac.uk/access/", "Official Trinity College access and outreach."),
    additional_source("Cambridge King's College Access", "University of Cambridge", "Academic", "University Outreach", "General / All Sectors", "https://www.kings.cam.ac.uk/study/access-and-outreach", "Official King's College Cambridge access and outreach."),
    additional_source("Cambridge St John's Access and Outreach", "University of Cambridge", "Academic", "University Outreach", "General / All Sectors", "https://www.joh.cam.ac.uk/access-and-outreach", "Official St John's College Cambridge access and outreach."),
    additional_source("Cambridge Caius Access and Outreach", "University of Cambridge", "Academic", "University Outreach", "General / All Sectors", "https://www.cai.cam.ac.uk/access-and-outreach", "Official Gonville and Caius access and outreach."),
    additional_source("Cambridge Pembroke Access and Outreach", "University of Cambridge", "Academic", "University Outreach", "General / All Sectors", "https://www.pem.cam.ac.uk/study-here/access-and-outreach", "Official Pembroke College Cambridge access and outreach."),
    additional_source("Cambridge Fitzwilliam Outreach", "University of Cambridge", "Academic", "University Outreach", "General / All Sectors", "https://www.fitz.cam.ac.uk/admissions/undergraduate-admissions/outreach", "Official Fitzwilliam College outreach."),
    additional_source("Cambridge Jesus College Access and Outreach", "University of Cambridge", "Academic", "University Outreach", "General / All Sectors", "https://www.jesus.cam.ac.uk/college/access-and-outreach", "Official Jesus College Cambridge access and outreach."),
    additional_source("Cambridge Newnham Access and Outreach", "University of Cambridge", "Academic", "University Outreach", "General / All Sectors", "https://www.newn.cam.ac.uk/admissions/undergraduates/access-and-outreach/", "Official Newnham College access and outreach."),
    additional_source("Cambridge Girton Access", "University of Cambridge", "Academic", "University Outreach", "General / All Sectors", "https://www.girton.cam.ac.uk/access", "Official Girton College access activity."),
    additional_source("Cambridge Murray Edwards Outreach", "University of Cambridge", "Academic", "University Outreach", "General / All Sectors", "https://www.murrayedwards.cam.ac.uk/study-us/undergraduates/outreach", "Official Murray Edwards College outreach."),
    additional_source("Cambridge Churchill College Outreach", "University of Cambridge", "Academic", "University Outreach", "General / All Sectors", "https://www.chu.cam.ac.uk/study-us/undergraduate/outreach/", "Official Churchill College outreach."),
    additional_source("Cambridge Mathematics Outreach", "University of Cambridge", "Academic", "University Outreach", "Mathematics", "https://www.maths.cam.ac.uk/outreach", "Official Cambridge Mathematics outreach."),
    additional_source("Cambridge Computer Laboratory Outreach", "University of Cambridge", "Academic", "University Outreach", "Computer Science", "https://www.cl.cam.ac.uk/admissions/undergraduate/outreach/", "Official Cambridge Computer Science outreach."),
    additional_source("University of Exeter Academic Competitions", "University of Exeter", "Academic", "Competition", "General / All Sectors", "https://www.exeter.ac.uk/study/discover-university/academiccompetitions/", "Official Exeter academic competitions."),
    additional_source("The Big Bang Fair", "EngineeringUK", "Academic", "Event", "STEM, Engineering, Science", "https://www.thebigbang.org.uk/", "Official Big Bang STEM event and competition hub."),
    additional_source("British Science Week", "British Science Association", "Academic", "Event", "STEM, Science", "https://www.britishscienceassociation.org/british-science-week", "Official British Science Week activities."),
    additional_source("TeenTech Awards", "TeenTech", "Academic", "Competition", "Technology, Engineering", "https://www.teentech.com/awards/", "Official TeenTech student innovation awards."),
    additional_source("FIRST LEGO League UK", "FIRST LEGO League", "Academic", "Competition", "Engineering, Technology, Computer Science", "https://www.firstlegoleague.co.uk/", "Official robotics competition for young people."),
    additional_source("VEX Robotics Competition", "VEX Robotics", "Academic", "Competition", "Engineering, Technology, Computer Science", "https://www.vexrobotics.com/competition", "Official VEX Robotics competition hub.", location="UK and international"),
    additional_source("Raspberry Pi Foundation", "Raspberry Pi Foundation", "Academic", "Course / Programme", "Computer Science, Technology", "https://www.raspberrypi.org/", "Official computing education projects and opportunities.", location="UK and international"),
    additional_source("Coolest Projects", "Raspberry Pi Foundation", "Creative", "Competition", "Computer Science, Technology, Creative", "https://coolestprojects.org/", "Official global technology showcase for young people.", location="UK and international"),
    additional_source("CyberCenturion", "Cyber Security Challenge UK", "Academic", "Competition", "Cyber Security, Computer Science", "https://www.cybersecuritychallenge.org.uk/cybercenturion", "Official cyber-security competition for schools."),
    additional_source("CanSat", "STEM Learning ESERO", "Academic", "Competition", "Space, Engineering, Physics", "https://www.stem.org.uk/esero/cansat", "Official CanSat space-engineering competition."),
    additional_source("UK Space Design Competition", "UK Space Design Competition", "Academic", "Competition", "Space, Engineering, Science", "https://uksdc.org/", "Official UK Space Design Competition."),
    additional_source("Integral Maths Ritangle", "Integral Maths", "Academic", "Competition", "Mathematics", "https://integralmaths.org/ritangle/", "Official online mathematics competition."),
    additional_source("Maths Feast", "Maths Feast", "Academic", "Competition", "Mathematics", "https://www.mathsfeast.org.uk/", "Official team mathematics competition."),
    additional_source("NRICH Mathematics", "University of Cambridge", "Academic", "Course / Programme", "Mathematics", "https://nrich.maths.org/", "Cambridge mathematics enrichment and problem-solving resources."),
    additional_source("Isaac Computer Science", "Isaac Computer Science", "Academic", "Course / Programme", "Computer Science", "https://isaaccomputerscience.org/", "Free computer-science learning and enrichment platform."),
    additional_source("Marshall Society Essay Competition", "Marshall Society", "Academic", "Essay Competition", "Economics", "https://www.marshallsociety.com/essay-competition", "Official economics essay competition."),
    additional_source("Discover Economics", "Discover Economics", "Careers", "Careers Programme", "Economics", "https://www.discovereconomics.ac.uk/", "Economics careers and student exploration hub."),
    additional_source("CORE Econ", "CORE Econ", "Academic", "Course / Programme", "Economics", "https://www.core-econ.org/", "Economics learning and enrichment resources."),
    additional_source("Observe GP", "Royal College of General Practitioners", "Careers", "Virtual Work Experience", "Medicine, Health", "https://www.rcgp.org.uk/your-career/observe-gp", "Official RCGP virtual work-experience resource."),
    additional_source("Industrial Cadets", "Engineering Development Trust", "Academic", "Course / Programme", "Engineering, Technology", "https://www.etrust.org.uk/industrial-cadets", "Official Industrial Cadets STEM experiences and awards."),
    additional_source("Minds Underground Competitions", "Minds Underground", "Academic", "Competition", "General / All Sectors", "https://www.mindsunderground.com/minds-underground-competitions", "Student competitions and academic enrichment."),
    additional_source("Paul Mellon Centre Write on Art", "Paul Mellon Centre", "Creative", "Essay Competition", "Art, History, Writing", "https://www.paul-mellon-centre.ac.uk/learning/about-write-on-art", "Official art-writing competition and learning opportunity."),
    additional_source("Young Poets Network", "The Poetry Society", "Creative", "Competition", "Writing, English", "https://ypn.poetrysociety.org.uk/", "Official poetry challenges and opportunities for young writers."),
    additional_source("National Gallery Articulation Prize", "National Gallery", "Creative", "Competition", "Art, History, Writing", "https://www.nationalgallery.org.uk/learning/secondary-schools/articulation/articulation-prize/articulation-prize-england", "Official Articulation Prize for secondary students."),
    additional_source("Tate Collective", "Tate", "Creative", "Course / Programme", "Art, Creative", "https://www.tate.org.uk/tate-collective", "Official Tate Collective opportunities for young people."),
    additional_source("Royal Academy Young People", "Royal Academy of Arts", "Creative", "Course / Programme", "Art, Creative", "https://www.royalacademy.org.uk/young-people", "Official Royal Academy young-person programmes."),
    additional_source("Into Film", "Into Film", "Creative", "Course / Programme", "Film, Media, Creative", "https://www.intofilm.org/", "Official film education opportunities for young people."),
    additional_source("ScreenSkills", "ScreenSkills", "Careers", "Careers Programme", "Film, Media, Creative", "https://www.screenskills.com/", "Screen-industry careers and skills opportunities."),
])


def record(source):
    return {**source, "deadline": None, "year_groups": None, "interests": None}


def main():
    if not SUPABASE_URL or not SUPABASE_KEY:
        raise SystemExit("Set SUPABASE_URL and SUPABASE_KEY GitHub secrets before running.")
    client = create_client(SUPABASE_URL, SUPABASE_KEY)
    inserted, updated = 0, 0
    for source in SOURCES:
        data = record(source)
        existing = client.table("opportunities").select("id").eq("link", source["link"]).limit(1).execute()
        if existing.data:
            client.table("opportunities").update(data).eq("id", existing.data[0]["id"]).execute()
            updated += 1
        else:
            client.table("opportunities").insert(data).execute()
            inserted += 1
    print(f"Verified public-source refresh complete: {inserted} inserted, {updated} updated.")


if __name__ == "__main__":
    main()
