#!/usr/bin/env python3
"""Refresh GrowthGrind's vetted public opportunity sources.

This deliberately imports only named providers and direct programme pages. It
does not scrape Google results, AI answers, social posts, or arbitrary sites.
Evergreen entries point students to a provider's current opportunities page;
the daily run updates them and leaves deadline fields empty rather than inventing
dates. Add a provider only after checking its public terms and student fit.
"""
import os
from supabase import create_client

SUPABASE_URL = os.environ.get("SUPABASE_URL")
SUPABASE_KEY = os.environ.get("SUPABASE_KEY")

SOURCES = [
    {"title": "The R3cruit 16–18 opportunities", "provider": "The R3cruit", "category": "Careers", "activity_type": "Work Experience", "location": "UK", "format": "Online and in-person", "age_range": "16-18", "cost": "Free", "subjects": "Finance, Business, Technology, Engineering", "link": "https://ther3cruit.co.uk/16-18-opportunities/", "description": "Frequently updated work experience, insight programmes, apprenticeships and career opportunities for 16–18-year-olds. Open the listing for live deadlines and direct application details."},
    {"title": "Prospects work experience and internships", "provider": "Prospects", "category": "Careers", "activity_type": "Work Experience", "location": "UK", "format": "Online and in-person", "age_range": "Check opportunity", "cost": "Free", "subjects": "General / All Sectors", "link": "https://www.prospects.ac.uk/jobs-and-work-experience/work-experience-and-internships/", "description": "Current guidance and routes to work experience and internships across sectors. Check individual opportunities for eligibility and application dates."},
    {"title": "The Brokerage Talent Network", "provider": "The Brokerage", "category": "Careers", "activity_type": "Work Experience", "location": "London / UK", "format": "Online and in-person", "age_range": "16-25", "cost": "Free", "subjects": "Business, Finance, Technology, General / All Sectors", "link": "https://www.thebrokerage.org.uk/talent-network", "description": "Talent network offering routes to internships, paid roles, employability support and employer opportunities for young people. Check current eligibility and openings directly."},
    {"title": "Futures for All opportunity finder", "provider": "Futures for All", "category": "Careers", "activity_type": "Opportunity Directory", "location": "UK", "format": "Online and in-person", "age_range": "Check opportunity", "cost": "Free", "subjects": "General / All Sectors", "link": "https://finder.futuresforall.org/opportunity-search?sortBy=AdvertiseStartAt&sortDirection=Ascending", "description": "Search a live directory of employer, education and skills opportunities. Use its filters to find currently open programmes and check each provider’s application requirements."},
    {"title": "Sutton Trust Pathways and UK Summer Schools", "provider": "The Sutton Trust", "category": "Academic", "activity_type": "Summer School", "location": "UK", "format": "Online and in-person", "age_range": "Year 12 / equivalent — check programme", "cost": "Free", "subjects": "Medicine, Law, Engineering, Finance, General / All Sectors", "link": "https://www.suttontrust.com/our-programmes/", "description": "Free widening-participation programmes, including Pathways, UK Summer Schools and online support. Check current eligibility, partner universities and application dates on the official Sutton Trust page."},
    {"title": "Oxford University outreach programmes", "provider": "University of Oxford", "category": "Academic", "activity_type": "University Outreach", "location": "UK", "format": "Online and in-person", "age_range": "Year 10+ / check programme", "cost": "Free", "subjects": "General / All Sectors", "link": "https://www.ox.ac.uk/admissions/undergraduate/access-oxford/outreach-programmes", "description": "Oxford's official access programmes, including UNIQ and BeUNIQ. Check individual programme eligibility, year-group and application details."},
    {"title": "Oxford University outreach events", "provider": "University of Oxford", "category": "Academic", "activity_type": "University Outreach", "location": "UK", "format": "Online and in-person", "age_range": "Check event", "cost": "Free / check event", "subjects": "General / All Sectors", "link": "https://www.ox.ac.uk/admissions/undergraduate/access-oxford/outreach-events", "description": "Oxford's current official outreach events, student conferences, subject taster activities and university-application information."},
    {"title": "Cambridge University widening participation and outreach", "provider": "University of Cambridge", "category": "Academic", "activity_type": "University Outreach", "location": "UK", "format": "Online and in-person", "age_range": "Check programme", "cost": "Free / check programme", "subjects": "General / All Sectors", "link": "https://www.cam.ac.uk/study-at-cambridge/widening-participation", "description": "Cambridge's official widening-participation and outreach information. Explore current events, regional programmes and school-student support."},
    {"title": "UCL widening participation opportunities", "provider": "University College London", "category": "Academic", "activity_type": "University Outreach", "location": "UK", "format": "Online and in-person", "age_range": "Check programme", "cost": "Free / check programme", "subjects": "General / All Sectors", "link": "https://www.ucl.ac.uk/prospective-students/widening-participation", "description": "UCL's official widening-participation programmes and resources for prospective students. Check individual eligibility and current events."},
    {"title": "Warwick University outreach and widening participation", "provider": "University of Warwick", "category": "Academic", "activity_type": "University Outreach", "location": "UK", "format": "Online and in-person", "age_range": "Check programme", "cost": "Free / check programme", "subjects": "General / All Sectors", "link": "https://warwick.ac.uk/study/outreach/", "description": "Warwick's official outreach and widening-participation activity for school and college students. Check programme availability and eligibility."},
    {"title": "Imperial College London widening participation", "provider": "Imperial College London", "category": "Academic", "activity_type": "University Outreach", "location": "London / UK", "format": "Online and in-person", "age_range": "Check programme", "cost": "Free / check programme", "subjects": "STEM, Medicine, General / All Sectors", "link": "https://www.imperial.ac.uk/widening-participation/", "description": "Imperial's official widening-participation hub for prospective students. Explore current access programmes, outreach events and eligibility on the university page."},
    {"title": "LSE schools and colleges widening participation", "provider": "London School of Economics and Political Science", "category": "Academic", "activity_type": "University Outreach", "location": "London / UK", "format": "Online and in-person", "age_range": "Check programme", "cost": "Free / check programme", "subjects": "Economics, Politics, Law, Social Sciences, General / All Sectors", "link": "https://www.lse.ac.uk/study-at-lse/undergraduate/widening-participation/teachers-and-schools", "description": "LSE's official schools, colleges and widening-participation information, including current events and support for prospective students."},
    {"title": "King's College London schools and colleges outreach", "provider": "King's College London", "category": "Academic", "activity_type": "University Outreach", "location": "London / UK", "format": "Online and in-person", "age_range": "Check programme", "cost": "Free / check programme", "subjects": "Medicine, Law, Health, Humanities, General / All Sectors", "link": "https://www.kcl.ac.uk/study/schools-and-colleges", "description": "King's official schools and colleges hub for outreach activities, events and guidance for prospective students."},
    {"title": "University of Bristol outreach and widening participation", "provider": "University of Bristol", "category": "Academic", "activity_type": "University Outreach", "location": "Bristol / UK", "format": "Online and in-person", "age_range": "Check programme", "cost": "Free / check programme", "subjects": "General / All Sectors", "link": "https://www.bristol.ac.uk/study/undergraduate/access-and-participation-plan/", "description": "Bristol's official access and participation hub, linking to outreach and widening-participation opportunities for schools, young people and mature students."},
    {"title": "University of Birmingham widening participation", "provider": "University of Birmingham", "category": "Academic", "activity_type": "University Outreach", "location": "Birmingham / UK", "format": "Online and in-person", "age_range": "Year 6-13 / check programme", "cost": "Free / check programme", "subjects": "Medicine, Law, Engineering, General / All Sectors", "link": "https://www.birmingham.ac.uk/study/undergraduate/schools-and-colleges/widening-participation", "description": "Birmingham's official widening-participation programmes, including Pathways to Birmingham, pre-16 activity and application support."},
    {"title": "University of Leeds access and outreach", "provider": "University of Leeds", "category": "Academic", "activity_type": "University Outreach", "location": "Leeds / UK", "format": "Online and in-person", "age_range": "Year 7+ / check programme", "cost": "Free / check programme", "subjects": "Arts, Health, Social Sciences, STEM, General / All Sectors", "link": "https://accessandoutreach.leeds.ac.uk/", "description": "Leeds' official access and outreach hub for pre-entry programmes, subject activities, school support and widening-access schemes."},
    {"title": "University of Manchester widening participation", "provider": "University of Manchester", "category": "Academic", "activity_type": "University Outreach", "location": "Manchester / UK", "format": "Online and in-person", "age_range": "Check programme", "cost": "Free / check programme", "subjects": "General / All Sectors", "link": "https://www.manchester.ac.uk/about/social-responsibility/social-inclusion/widening-participation/", "description": "Manchester's official widening-participation hub. Explore access schemes, outreach support and current opportunities for prospective students."},
    {"title": "University of Sheffield Access to Sheffield", "provider": "University of Sheffield", "category": "Academic", "activity_type": "University Outreach", "location": "Sheffield / UK", "format": "Online and in-person", "age_range": "Year 9-13 / check programme", "cost": "Free / check programme", "subjects": "General / All Sectors", "link": "https://www.sheffield.ac.uk/schools/programmes", "description": "Sheffield's official Access to Sheffield hub, with widening-access programmes, post-16 summer schools and application support."},
    {"title": "University of Nottingham widening participation programmes", "provider": "University of Nottingham", "category": "Academic", "activity_type": "University Outreach", "location": "Nottingham / UK", "format": "Online and in-person", "age_range": "Check programme", "cost": "Free / check programme", "subjects": "Medicine, Veterinary Science, General / All Sectors", "link": "https://www.nottingham.ac.uk/support-services/home/widening-participation-and-outreach/our-programmes.html", "description": "Nottingham's official widening-participation programme hub, with pathways, summer schools and university-application support."},
    {"title": "University of Liverpool widening participation and outreach", "provider": "University of Liverpool", "category": "Academic", "activity_type": "University Outreach", "location": "Liverpool / UK", "format": "Online and in-person", "age_range": "Key Stage 3-5 / check programme", "cost": "Free / check programme", "subjects": "Medicine, Health, General / All Sectors", "link": "https://www.liverpool.ac.uk/study/widening-participation/", "description": "Liverpool's official widening-participation and outreach hub, including academic mentoring, access programmes and post-16 support."},
    {"title": "University of York widening access", "provider": "University of York", "category": "Academic", "activity_type": "University Outreach", "location": "York / UK", "format": "Online and in-person", "age_range": "Pre-16 and post-16 / check programme", "cost": "Free / check programme", "subjects": "General / All Sectors", "link": "https://www.york.ac.uk/schools-and-colleges/widening-access/", "description": "York's official widening-access hub with pre-16 and post-16 activities, talks, campus visits and support for prospective students."},
    {"title": "Forage virtual job simulations", "provider": "Forage", "category": "Careers", "activity_type": "Virtual Work Experience", "location": "International / online", "format": "Online", "age_range": "Check provider eligibility", "cost": "Free", "subjects": "Business, Technology, Law, Finance", "link": "https://www.theforage.com/", "description": "Free employer-designed virtual job simulations. Browse current programmes and complete one at your own pace; availability and eligibility are shown by the provider."},
    {"title": "Springpod virtual work experience", "provider": "Springpod", "category": "Careers", "activity_type": "Virtual Work Experience", "location": "UK / online", "format": "Online", "age_range": "Check provider eligibility", "cost": "Free / check provider", "subjects": "Medicine, Business, Law, Technology, Engineering", "link": "https://www.springpod.com/virtual-work-experience", "description": "Browse current virtual work-experience programmes and provider eligibility directly with Springpod."},
    {"title": "Speakers for Schools work experience", "provider": "Speakers for Schools", "category": "Careers", "activity_type": "Work Experience", "location": "UK", "format": "Online and in-person", "age_range": "Check provider eligibility", "cost": "Free", "subjects": "General / All Sectors", "link": "https://www.speakersforschools.org/experience/", "description": "Current work-experience opportunities for young people. Check the provider page for open placements, dates and eligibility."},
    {"title": "Nuffield Research Placements", "provider": "Nuffield Foundation", "category": "Academic", "activity_type": "Research", "location": "UK", "format": "In-person and hybrid", "age_range": "Post-16 / check provider", "cost": "Free", "subjects": "Science, Research & Sustainability", "link": "https://www.nuffieldresearchplacements.org/", "description": "Research placements for eligible post-16 students. Check regional availability, timetable and application criteria on the official page."},
    {"title": "FutureLearn short courses and certificates", "provider": "FutureLearn", "category": "Academic", "activity_type": "Course / Programme", "location": "International / online", "format": "Online", "age_range": "Check provider eligibility", "cost": "Free and paid options", "subjects": "General / All Sectors", "link": "https://www.futurelearn.com/courses", "description": "Explore current online short courses from universities and cultural institutions. Course access and certificate options vary."},
    {"title": "OpenLearn free courses", "provider": "The Open University", "category": "Academic", "activity_type": "Course / Programme", "location": "International / online", "format": "Online", "age_range": "Open access / check course", "cost": "Free", "subjects": "General / All Sectors", "link": "https://www.open.edu/openlearn/free-courses", "description": "Free online courses across subjects. Check individual course pages for study time and digital badges."},
    {"title": "National Saturday Club", "provider": "National Saturday Club", "category": "Creative", "activity_type": "Course / Programme", "location": "UK", "format": "In-person", "age_range": "13-16", "cost": "Free", "subjects": "Art, Design, Technology", "link": "https://www.nationalsaturdayclub.org/", "description": "Saturday clubs in art, design, science, technology and performance. Check local club availability and current application details."},
    {"title": "Duke of Edinburgh's Award", "provider": "DofE", "category": "Leadership", "activity_type": "Leadership Programme", "location": "International", "format": "In-person and hybrid", "age_range": "14+", "cost": "Check provider", "subjects": "Leadership, Volunteering, Sport", "link": "https://www.dofe.org/", "description": "Structured volunteering, physical, skills and expedition challenges. Check local centre availability and participation costs."},
    {"title": "Do-it volunteering opportunities", "provider": "Do-it", "category": "Volunteering", "activity_type": "Volunteering", "location": "UK", "format": "Online and in-person", "age_range": "Check organisation eligibility", "cost": "Free", "subjects": "General / All Sectors", "link": "https://doit.life/", "description": "Search current volunteering roles by location and cause. Each organisation sets its own age and safeguarding requirements."},
    {"title": "British Science Association CREST Awards", "provider": "British Science Association", "category": "Academic", "activity_type": "Research", "location": "UK and international", "format": "Online and in-person", "age_range": "11-19", "cost": "Check provider", "subjects": "Science, Research & Sustainability", "link": "https://www.crestawards.org/", "description": "Student-led STEM project awards. Check current project formats, costs and school participation guidance."},
    {"title": "UK Mathematics Trust competitions", "provider": "UK Mathematics Trust", "category": "Academic", "activity_type": "Competition", "location": "UK", "format": "School-based", "age_range": "Check competition", "cost": "Check school / provider", "subjects": "Mathematics", "link": "https://ukmt.org.uk/competitions", "description": "Current mathematics challenges, olympiads and team competitions. Check the relevant competition’s year-group and entry details."},
    {"title": "Erasmus+ Youth opportunities", "provider": "European Youth Portal", "category": "International", "activity_type": "International Programme", "location": "International", "format": "Online and in-person", "age_range": "Check opportunity", "cost": "Varies", "subjects": "Languages, Leadership, Volunteering", "link": "https://youth.europa.eu/go-abroad_en", "description": "Explore current international youth exchanges, volunteering and mobility opportunities. Eligibility depends on residence, age and host programme."},
    {"title": "LTA junior tennis competitions", "provider": "LTA", "category": "Sport", "activity_type": "Competition", "location": "UK", "format": "In-person", "age_range": "Junior / check event", "cost": "Check event", "subjects": "Tennis, Sport", "link": "https://www.lta.org.uk/compete/junior/", "description": "Official LTA hub for junior tennis competition, from beginner matchplay and local tournaments to county and national pathways. Find current events and age eligibility."},
    {"title": "LTA youth tennis leadership and volunteering", "provider": "LTA", "category": "Sport", "activity_type": "Leadership Programme", "location": "UK", "format": "In-person and hybrid", "age_range": "11-18", "cost": "Free / check local delivery", "subjects": "Tennis, Sport, Leadership, Volunteering", "link": "https://www.lta.org.uk/roles-and-venues/volunteers/become-a-tennis-volunteer/", "description": "LTA's official tennis-volunteering guide, including LTA Youth Tennis Leaders for 11-18-year-olds, local competition volunteering and leadership pathways."},
    {"title": "Badminton England competitions", "provider": "Badminton England", "category": "Sport", "activity_type": "Competition", "location": "England / UK", "format": "In-person", "age_range": "Junior / check tournament", "cost": "Check tournament", "subjects": "Badminton, Sport", "link": "https://www.badmintonengland.co.uk/competition/", "description": "Official Badminton England competition hub. Use the tournament system to find current junior, club and national badminton competitions."},
    {"title": "Badminton England volunteering", "provider": "Badminton England", "category": "Sport", "activity_type": "Volunteering", "location": "England / UK", "format": "In-person", "age_range": "Check role", "cost": "Free", "subjects": "Badminton, Sport, Leadership", "link": "https://www.badmintonengland.co.uk/volunteers/", "description": "Official Badminton England volunteering information and routes to major-event, club and competition volunteering. Check individual role age requirements."},
    {"title": "Badminton England club and junior session finder", "provider": "Badminton England", "category": "Sport", "activity_type": "Sport Programme", "location": "England / UK", "format": "In-person", "age_range": "Juniors / check session", "cost": "Free and paid options", "subjects": "Badminton, Sport", "link": "https://www.badmintonengland.co.uk/play/", "description": "Find affiliated badminton clubs, junior sessions and official participation programmes. Local sessions set their own age, price and booking details."},
    {"title": "Powerleague local football leagues", "provider": "Powerleague", "category": "Sport", "activity_type": "Sport Programme", "location": "UK", "format": "In-person", "age_range": "Check venue", "cost": "Check venue", "subjects": "Football, Sport", "link": "https://www.powerleague.co.uk/", "description": "Find local small-sided football leagues and venues. Check each venue for youth availability, team entry rules and current prices."},
    {"title": "School Games sport, competition and leadership", "provider": "School Games", "category": "Sport", "activity_type": "Competition", "location": "England / UK", "format": "School-based and in-person", "age_range": "School age", "cost": "Free through participating schools", "subjects": "Multi-sport, Sport, Leadership", "link": "https://www.yourschoolgames.com/", "description": "Official School Games hub for school sport, local competitions, youth leadership and volunteering. Ask your school or School Games Organiser about local activity."},
    {"title": "Youth Sport Trust young leader training", "provider": "Youth Sport Trust", "category": "Sport", "activity_type": "Leadership Programme", "location": "England / UK", "format": "School-based", "age_range": "11-14", "cost": "Free through schools", "subjects": "Sport, Leadership", "link": "https://www.youthsporttrust.org/young-leader-training", "description": "Free young-leader training resources that help secondary pupils plan, lead and review inclusive physical activity in school. Delivered by a school or youth-sport leader."},
    {"title": "London Youth Games Open Games", "provider": "London Youth Games", "category": "Sport", "activity_type": "Competition", "location": "London", "format": "In-person", "age_range": "7-17 / check sport", "cost": "Free / check borough", "subjects": "Multi-sport, Sport", "link": "https://www.londonyouthgames.org/open-games-how-to-compete/", "description": "Europe's largest community youth sporting competition across 37 sports. Open to young people who live or attend school in a London borough; register through your Borough Team Organiser."},
    {"title": "London Youth Games GamesForce volunteering", "provider": "London Youth Games", "category": "Sport", "activity_type": "Volunteering", "location": "London", "format": "In-person", "age_range": "14+ / check role", "cost": "Free", "subjects": "Multi-sport, Sport, Leadership, Media", "link": "https://www.londonyouthgames.org/volunteer/", "description": "Volunteer in sport, event delivery, media or officiating with London Youth Games. GamesForce Teams welcomes young leaders aged 14+ through schools, colleges and universities."},
]


def record(source):
    return {**source, "deadline": None, "year_groups": None, "interests": None}


def main():
    if not SUPABASE_URL or not SUPABASE_KEY:
        raise SystemExit("Set SUPABASE_URL and SUPABASE_KEY GitHub secrets before running.")
    client = create_client(SUPABASE_URL, SUPABASE_KEY)
    inserted, updated = 0, 0
    for source in SOURCES:
        data = record(source)
        existing = client.table("opportunities").select("id").eq("link", source["link"]).limit(1).execute()
        if existing.data:
            client.table("opportunities").update(data).eq("id", existing.data[0]["id"]).execute()
            updated += 1
        else:
            client.table("opportunities").insert(data).execute()
            inserted += 1
    print(f"Verified public-source refresh complete: {inserted} inserted, {updated} updated.")


if __name__ == "__main__":
    main()
